# signup-service/Dockerfile
FROM node:14

COPY . /Signup

WORKDIR /Signup

RUN apt-get update
RUN apt-get install git -y
RUN apt-get install nodejs -y
RUN apt-get install npm -y

EXPOSE 3001

CMD ["node", "signup-service.js"]